- name: Replace environment variables in index.html
  run: |
    sed -i "s|YOUR-API-KEY|${{ secrets.BRAZE_API_KEY }}|g" index.html
    sed -i "s|YOUR-REST-ENDPOINT|${{ secrets.BRAZE_REST_ENDPOINT }}|g" index.html
